name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Checkout build environment
      uses: actions/checkout@v2
      with:
        ref: main
        path: build-environment

    - name: Install Dependencies
      run: cd build-environment && yarn install

    - name: Build
      run: cd build-environment && yarn run build

    - name: Update
      run: |
        cp -a build-environment/build/* .
        rm -rf build-environment

    - name: Commit
      id: commit
      run: |
        git config --global user.email "paketobuildpacks@gmail.com"
        git config --global user.name "paketo-bot"

        if [[ -n "$(git status --short)" ]]; then
          git add --all .
          git commit --message "Deploying"
          echo "::set-output name=commit_sha::$(git rev-parse HEAD)"
        fi

    - name: Push
      if: ${{ steps.commit.outputs.commit_sha != '' }}
      run: git push origin gh-pages
