name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn run build

    - name: Push
      run: |
        set -x

        mv ./build /tmp
        git rm -r .
        cp -a /tmp/build/* .

        ls -al .

