name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

    - name: Authenticate with GCR
      env:
        GCR_PUSH_BOT_JSON_KEY: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
      run: |
        echo "${GCR_PUSH_BOT_JSON_KEY}" | docker login --username _json_key --password-stdin gcr.io

    - name: Setup pack
      uses: buildpacks/github-actions/setup-pack@v5.3.1

    - name: Pack Build
      run: |
        pack build gcr.io/paketo-buildpacks/dashboard \
          --builder paketobuildpacks/builder:buildpackless-base \
          --publish

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_RUN_SERVICE_ACCOUNT_KEY }}
        
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1.1.1

    - name: Deploy
      env:
        GITHUB_CLIENT_ID: ${{ secrets.DASHBOARD_GITHUB_CLIENT_ID }}
        GITHUB_CLIENT_SECRET: ${{ secrets.DASHBOARD_GITHUB_CLIENT_SECRET }}
        REDIRECT_URI: ${{ secrets.DASHBOARD_REDIRECT_URI }}
      run: |
        gcloud run services update dashboard \
          --region us-central1 \
          --image gcr.io/paketo-buildpacks/dashboard:latest \
          --set-env-vars="GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID},GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET},REDIRECT_URI=${REDIRECT_URI}"
