name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Checkout build environment
      uses: actions/checkout@v2
      with:
        ref: main
        path: build-environment

    - name: Install Dependencies
      run: cd build-environment && yarn install

    - name: Build
      run: cd build-environment && yarn run build

    - name: Update
      run: |
        cp -a build-environment/build/* .
        rm -rf build-environment

    - name: Commit
      run: |
        git config --global user.email "ryan.moran@gmail.com"
        git config --global user.name "Ryan Moran"

        git add --all .
        git commit --message "Deploying"

    - name: Push
      run: git push origin gh-pages
