name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install

    - name: Build
      run: yarn run build

    - name: Prepare
      run: |
        mv ./build /tmp
        git clean -ffdx
        git rm -r .
        cp -a /tmp/build/* .

    - name: Commit
      run: |
        git config --global user.email "ryan.moran@gmail.com"
        git config --global user.name "Ryan Moran"

        git add --all .
        git commit --message "Deploying"

    - name: Push
      run: git push origin gh-pages
