name: Test Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install

    - name: Run Tests
      run: CI=true yarn run test

    - name: Type Check
      run: yarn run flow
