name: Test Pull Request

on:
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19.x

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Frontend Dependencies
      run: cd web && yarn install

    - name: Run Frontend Tests
      run: cd web && CI=true yarn run test

    - name: Type Check Frontend
      run: cd web && yarn run flow

    - name: Run Backend Tests
      run: go test -v ./server
